"""empty message

Revision ID: 65564c7b6623
Revises: b0b795560aa1
Create Date: 2025-01-16 13:53:26.489141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65564c7b6623'
down_revision = 'b0b795560aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('room_select',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('room_select',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
